### ISSUE TITLE
only support IOS 13 or above？

### ISSUE THREAD

**Issue by dolin-tan** [xmarkclx/cordova-plugin-photo-library-sism#2]
Hello, does it only support IOS 13 or above? Because there's a flash back on IOS 12，thank you

**Comment by xmarkclx** [comment]
I only tested it on the latest iOS versions as my test devices are always updated and Apple disallows downgrading to prev versions by revoking install certificates.

**Comment by dolin-tan** [comment]
@xmarkclx I got it thank you
