### ISSUE TITLE
Add Swift Support dependency still required?

### ISSUE THREAD

**Issue by AndrianLeah** [xmarkclx/cordova-plugin-photo-library-sism#3]
Is the cordova-plugin-add-swift-support still required? 
<s>It's not compatible with xcode 11 and swift compatibility should be included in cordova-ios 5+</s>

edit: had to update add-swift-support to 2.0.2

**Comment by xmarkclx** [comment]
That's really odd, I use XCode 11.4.1 and use this plugin on Ionic 5/Angular 9.

**Comment by AndrianLeah** [comment]
Sorry it was my mistake, I've edited the issue.
The plugin works perfectly
